# setup_resumes.ps1
# Creates resume-library structure + generates DOCX/TXT resumes using python-docx
# FIXES:
# 1) Avoids resume-library\resume-library nesting
# 2) Robust Python detection (py -> python) + docx install

param(
  [string]$RepoRoot = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

# -------------------------
# Normalize RepoRoot
# -------------------------
# If user is already inside a folder named "resume-library", keep it.
# Otherwise, create/use a child folder named "resume-library".
$leaf = Split-Path -Path $RepoRoot -Leaf
if ($leaf -ne "resume-library") {
  $RepoRoot = Join-Path $RepoRoot "resume-library"
}

if (-not (Test-Path $RepoRoot)) {
  New-Item -ItemType Directory -Path $RepoRoot | Out-Null
  Write-Host "Created root folder: $RepoRoot"
} else {
  Write-Host "Root exists: $RepoRoot"
}
Write-Host "Using Root: $RepoRoot"

# -------------------------
# Python detection
# -------------------------
function Get-PythonCommand {
  # Prefer Windows py launcher
  $py = Get-Command py -ErrorAction SilentlyContinue
  if ($py) { return @("py", "-3") }

  $python = Get-Command python -ErrorAction SilentlyContinue
  if ($python) { return @("python") }

  $python3 = Get-Command python3 -ErrorAction SilentlyContinue
  if ($python3) { return @("python3") }

  return $null
}

$pyCmd = Get-PythonCommand
if (-not $pyCmd) {
  throw "Python not found. Install Python 3.x (and ensure 'py' or 'python' is available in PATH), then rerun."
}

Write-Host "Python command: $($pyCmd -join ' ')"

# -------------------------
# Create folder structure
# -------------------------
$paths = @(
  "$RepoRoot\resumes",
  "$RepoRoot\resumes\general",
  "$RepoRoot\resumes\python-backend",
  "$RepoRoot\resumes\cybersecurity",
  "$RepoRoot\resumes\ai-architect"
)

foreach ($p in $paths) {
  if (-not (Test-Path $p)) {
    New-Item -ItemType Directory -Path $p | Out-Null
    Write-Host "Created: $p"
  } else {
    Write-Host "Exists:  $p"
  }
}

# -------------------------
# Create README
# -------------------------
$readmePath = "$RepoRoot\resumes\README.md"
@"
# Resume Library (Versioned)

This folder contains role-targeted resume variants for Brian Hannigan.

## Structure
- `general/`        Master resume (broad)
- `python-backend/` Python backend engineer variant
- `cybersecurity/`  SIEM / Detection / GRC variant
- `ai-architect/`   AI systems architect variant

## Generation
Files are generated by `generate_resumes.py` using `python-docx`.
TXT versions are included for ATS checks and easy copy/paste.
"@ | Set-Content -Encoding UTF8 $readmePath
Write-Host "Wrote: $readmePath"

# -------------------------
# Create generator script
# -------------------------
$genPath = "$RepoRoot\generate_resumes.py"
@"
from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "resumes"

NAME = "BRIAN HANNIGAN"
PHONE = "(862) 243-1177"
EMAIL = "jobshannigan@gmail.com"
LINKEDIN = "linkedin.com/in/brianjhannigan"
GITHUB = "github.com/brianhannigan"
LOCATION = "Remote | 07876"

def set_doc_margins(doc: Document):
    section = doc.sections[0]
    section.top_margin = Inches(0.6)
    section.bottom_margin = Inches(0.6)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

def add_title(doc: Document, text: str):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(16)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

def add_subtitle(doc: Document, text: str):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(10.5)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

def add_section(doc: Document, title: str):
    p = doc.add_paragraph()
    run = p.add_run(title.upper())
    run.bold = True
    run.font.size = Pt(11.5)

def add_bullets(doc: Document, bullets):
    for b in bullets:
        p = doc.add_paragraph(b, style="List Bullet")
        for r in p.runs:
            r.font.size = Pt(10.5)

def add_paragraph(doc: Document, text: str):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(10.5)

def save_txt(path: Path, lines):
    path.write_text("\\n".join(lines).strip() + "\\n", encoding="utf-8")

def build_python_backend():
    summary = (
        "Backend-focused Python Engineer and Systems Architect with 15+ years building secure, scalable systems in "
        "mission-critical environments. Experienced in designing RESTful APIs, building modular Python services, integrating "
        "databases, and deploying production-ready applications. Strong foundation in OOP, data structures, debugging, and "
        "performance optimization."
    )

    skills = [
        "Languages: Python, C#, SQL, Bash",
        "Backend: REST APIs, JSON, HTTP, Service-Oriented Architecture",
        "Framework Exposure: FastAPI-style architectures, Flask concepts",
        "Databases: SQLite, SQL Server, MySQL, PostgreSQL (conceptual familiarity)",
        "Tools: Git, Docker, Linux, Windows",
        "Concepts: OOP, Data Structures, Algorithms, API Design, Logging, Error Handling",
        "Security: Secure coding practices, compliance-focused engineering",
        "Process: Agile, Code Reviews, Version Control Workflows",
    ]

    project_title = "Portable Translator — Python Backend & API Services (GitHub: github.com/brianhannigan/translator)"
    project_bullets = [
        "Designed and implemented Python-based REST services supporting OCR and AI translation workflows.",
        "Built HTTP endpoints handling structured JSON request/response patterns.",
        "Integrated OCR and local translation engines into a modular service architecture.",
        "Implemented logging, process monitoring, and structured error handling for reliability.",
        "Used Git-based version control and iterative feature development practices.",
    ]

    exp_title = "UTRS, Inc — Lead Technical Systems Engineer | 2011–2025"
    exp_bullets = [
        "Developed backend utilities and automation scripts in Python for system validation and configuration workflows.",
        "Designed modular software components supporting data processing and system integration.",
        "Applied structured debugging techniques to improve performance and reliability across deployments.",
        "Participated in version control workflows and iterative delivery of enhancements and fixes.",
        "Implemented secure configuration standards aligned with compliance expectations.",
    ]

    edu = [
        "B.S., Criminal Justice — University of Delaware",
        "M.Ed., Special Education — New Jersey City University",
        "Programming Diploma — Chubb Institute",
    ]

    highlights = [
        "Production deployment experience",
        "REST API design and implementation",
        "Modular backend service architecture",
        "Structured logging, debugging, and reliability practices",
        "Database integration patterns",
        "Security-first engineering mindset",
    ]

    # DOCX
    doc = Document()
    set_doc_margins(doc)

    add_title(doc, NAME)
    add_subtitle(doc, f"{LOCATION} | {PHONE} | {EMAIL}")
    add_subtitle(doc, f"LinkedIn: {LINKEDIN} | GitHub: {GITHUB}")

    add_section(doc, "Professional Summary")
    add_paragraph(doc, summary)

    add_section(doc, "Technical Skills")
    add_bullets(doc, skills)

    add_section(doc, "Featured Python Project")
    p = doc.add_paragraph()
    r = p.add_run(project_title)
    r.bold = True
    r.font.size = Pt(10.75)
    add_bullets(doc, project_bullets)

    add_section(doc, "Professional Experience")
    p = doc.add_paragraph()
    r = p.add_run(exp_title)
    r.bold = True
    r.font.size = Pt(10.75)
    add_bullets(doc, exp_bullets)

    add_section(doc, "Education")
    add_bullets(doc, edu)

    add_section(doc, "Engineering Highlights")
    add_bullets(doc, highlights)

    docx_path = OUT / "python-backend" / "brian-hannigan-python-backend.docx"
    txt_path  = OUT / "python-backend" / "brian-hannigan-python-backend.txt"
    docx_path.parent.mkdir(parents=True, exist_ok=True)

    doc.save(str(docx_path))

    # TXT (ATS)
    lines = []
    lines.append(NAME)
    lines.append(f"{LOCATION} | {PHONE} | {EMAIL}")
    lines.append(f"LinkedIn: {LINKEDIN} | GitHub: {GITHUB}")
    lines.append("")
    lines.append("PROFESSIONAL SUMMARY")
    lines.append(summary)
    lines.append("")
    lines.append("TECHNICAL SKILLS")
    lines.extend(skills)
    lines.append("")
    lines.append("FEATURED PYTHON PROJECT")
    lines.append(project_title)
    for b in project_bullets:
        lines.append(f"- {b}")
    lines.append("")
    lines.append("PROFESSIONAL EXPERIENCE")
    lines.append(exp_title)
    for b in exp_bullets:
        lines.append(f"- {b}")
    lines.append("")
    lines.append("EDUCATION")
    for e in edu:
        lines.append(f"- {e}")
    lines.append("")
    lines.append("ENGINEERING HIGHLIGHTS")
    for h in highlights:
        lines.append(f"- {h}")

    save_txt(txt_path, lines)

    return docx_path, txt_path

def main():
    docx_path, txt_path = build_python_backend()

    # Keep other folders in repo
    for track in ["general", "cybersecurity", "ai-architect"]:
        (OUT / track / ".keep").write_text("keep\\n", encoding="utf-8")

    print("Generated:")
    print(f"- {docx_path}")
    print(f"- {txt_path}")

if __name__ == "__main__":
    main()
"@ | Set-Content -Encoding UTF8 $genPath
Write-Host "Wrote: $genPath"

# -------------------------
# Ensure python-docx
# -------------------------
Write-Host "Checking python-docx..."
& $pyCmd[0] $pyCmd[1] -c "import docx; print('python-docx OK')" 2>$null
if ($LASTEXITCODE -ne 0) {
  Write-Host "python-docx not found. Installing..."
  if ($pyCmd[0] -eq "py") {
    & py -3 -m pip install --upgrade pip
    & py -3 -m pip install python-docx
  } else {
    & $pyCmd[0] -m pip install --upgrade pip
    & $pyCmd[0] -m pip install python-docx
  }
}

# -------------------------
# Generate resumes
# -------------------------
Write-Host "Generating resumes..."
if ($pyCmd[0] -eq "py") {
  & py -3 $genPath
} else {
  & $pyCmd[0] $genPath
}

Write-Host ""
Write-Host "Done. Files created under: $RepoRoot\resumes"